set autoindent
set backspace=indent,start,eol
set nobackup
set backupcopy=yes
set belloff=all
set completeopt=menu,menuone,noselect
set nocursorline
set noemoji
set expandtab
set formatoptions=tcqjn
set hidden
set ignorecase
set incsearch
set nojoinspaces
set laststatus=1
set linebreak
set list
set listchars=tab:>\ ,trail:\\x20
set modelines=5
set mouse=a
set showmode
set path+=**
set ruler
set scrolloff=3
set noshiftround
set shiftwidth=4
set shortmess=fixtmToO
set noshowcmd
set smartcase
set smarttab
set splitbelow
set splitright
set noswapfile
set termwinkey=<C-X>
set textwidth=80
set title
set titlestring=%t\ -\ vim
set ttimeoutlen=1
set undodir=$HOME/.vim/tmp/undo/
set undofile
set updatetime=500
set updatecount=0
set virtualedit=block
set wildmenu
set wildmode=longest:list,full
set nowrap
set nowritebackup

" GUI settings
if has("gui_running")
    set guioptions=egmti
endif

" Set global leader key
let mapleader=','

" Set cursor shape
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" Set colorscheme
if &t_Co > 2 || has("gui_running")
    syntax on
    colorscheme jason
endif

" Detect the filetypes
if version > 580
    filetype indent plugin on
endif

" Easier window split movement
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Intuitive movement
noremap j gj
noremap k gk

" Saving and quiting
nnoremap <Leader>q :q<CR>
nnoremap <Leader>w :w<CR>

" Quickly move lines up and down
xnoremap <silent> J :m'>+<CR>gv=gv
xnoremap <silent> K :m-2<CR>gv=gv

" Local settings for plain-text writing
function! WritingMode()
    setlocal wrap
    setlocal colorcolumn=80
    setlocal conceallevel=0
    setlocal comments=b:*,b:-,b:+,n:>
    setlocal formatoptions=jnr
    setlocal shiftwidth=2
    setlocal tabstop=2
endfunction

if has('autocmd')
    autocmd BufReadPost *
                \ if line("'\"") > 0 && line("'\"") <= line("$") |
                \   exe "normal! g`\"" |
                \ endif

    let s:whitespace_ignore = ['gitcommit', 'diff']
    autocmd BufWritePre * if index(s:whitespace_ignore, &ft) < 0 | %s/\s\+$//e

    autocmd Filetype gitcommit,markdown call WritingMode()

    autocmd Filetype python set colorcolumn=80

    autocmd VimResized * wincmd =
endif
