#!/bin/bash

arg_len=$#
args=$@

function checkRunningTmux() {
  if [[ -n $(pgrep tmux) ]]; then
    echo 1
  else
    echo 0
  fi
}

function checkTitle() {
  echo $1 | grep ':' > /dev/null

  if [[ $? -eq 0 ]]; then
    echo 1
  else
    echo 0
  fi
}


function ask_prompt() {
	read -p "$1" yn
	case $yn in
		[Yy]* ) $2 ;;
		[Nn]* ) $3 ;;
		* ) echo "Please answer yes or no.";;
	esac
}

function tmux() {

  if [[ $(checkRunningTmux) -eq 1 ]]; then
    echo "There is already a tmux sessions running"
		ask_prompt "Do you still want to make a new session? " "echo Continuing..." "exit 1"
  fi

  tmux_command="tmux -2 new\;"

  for (( i=1; i <= $arg_len; i++ )); do
    local cur_arg=$(echo $args | awk -v ind="$i" '{printf "%s\n", $ind}')

    # Grab the title and the program name
    if [[ $(checkTitle $cur_arg) -eq 1 ]]; then
      local program=$(echo "$cur_arg" | cut -d':' -f1)
      local title=$(echo "$cur_arg" | cut -d':' -f2)
    else
      local program=$(echo "$cur_arg")
      local title=$(echo "$cur_arg")
    fi

    echo -e "$program\n$title"

    tmux_command+=" neww -n '$title' $program\;"
  done
}

tmux
bash -c "$tmux_command"
