export EDITOR="vim"
export GIT_EDITOR=$EDITOR
export PAGER="less"
export TERM="xterm-256color"
export TERMINAL="xterm-256color"
export VISUAL=$EDITOR

# Shell specific
export HISTFILE="$HOME/.zsh_history"
export HISTSIZE=12000
export SAVEHIST=$HISTSIZE
export WORDCHARS='*?_-.[]~=&;!#%^(){}<>'
