FZY_DEFAULT_OPTS=('--show-info' '--lines=30' '--prompt=>> ')
PATH="$PATH:$ZDOTDIR/scripts/:$HOME/.cargo/bin"
KEYTIMEOUT=1
VISUAL="vim"
EDITOR="vim"
TERMINAL="st"
HIST_STAMPS="mm.dd.yyyy"
HISTSIZE=12000
SAVEHIST=12000
HISTFILE="$HOME/.zsh_history"
TERM="st-256color"
WORDCHARS='*?_-.[]~=&;!#%^(){}<>'
