alias v='vim'
alias vi='vim'
alias cp='cp -v'
alias mv='mv -v'
alias man='nocorrect man'
alias mkdir='nocorrect mkdir'
alias mv='nocorrect mv'
alias sudo='nocorrect sudo'
alias docker='nocorrect docker'

case $(uname) in
    Linux) alias ls='ls --color=always --group-directories' ;;
    FreeBSD) alias ls='ls --color=always' ;;
    *) ;;
esac

bindkey -e
bindkey '^b' backward-word
bindkey '^f' forward-word
bindkey '^j' kill-word

autoload -Uz compinit
autoload -U +X bashcompinit && bashcompinit
compinit

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format ''
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SList: %p%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select
zstyle ':completion:*' select-prompt %SList: %p%s
zstyle ':completion:*' use-compctl false
zstyle ':completion:*' verbose true
zstyle ':completion:*:history-words' stop yes
zstyle ':completion:*:history-words' remove-all-dups yes
zstyle ':completion:*:history-words' list false
zstyle ':completion:*:history-words' menu yes

setopt append_history
setopt extended_history
setopt sharehistory
setopt hist_reduce_blanks
setopt always_to_end
setopt complete_in_word
setopt auto_menu
setopt correct
setopt correctall
setopt list_packed

CLEAR="%{%b%f%}"
RED="%{%F{9}%}"
BLUE="%{%F{12}%}"
YELLOW="%{%F{11}%}"
GREEN_YELLOW="%{%F{154}%}"

# Text changes
BOLD_START="%B"
BOLD_END="%b"

# Set window title in xterm
function precmd {
    case $TERM in
        xterm*|rxvt*) print -Pn "\e]0;%1d - zsh\a" ;;
        *) ;;
    esac
}

export PROMPT="$BOLD_START$YELLOW%n$CLEAR@$BOLD_START$GREEN_YELLOW%m$CLEAR:$BOLD_START$BLUE%(4~|../%3~|%~)$CLEAR$BOLD_END%# "
export SPROMPT="zsh: correct $BOLD_START$RED'%R'$CLEAR$BOLD_END to $BOLD_START$RED'%r'$CLEAR$BOLD_END [nyae]? "

if [ -f "$HOME/.zshrc.local" ]; then
   source "$HOME/.zshrc.local"
fi
